In [1]:
import sys
# appending a path
sys.path.append('../')

import jax
import torch
import numpy as np
from pychop.chop import Chop
from scipy.io import loadmat
import pychop

# pychop.backend('torch')
pychop.backend('numpy', 1) # print information, NumPy is the default option.
X_np = loadmat("verified_data.mat")
X_np = X_np['array'][0]

Load NumPy backend.


In [2]:
ch = Chop('h', rmode=1, subnormal=0)
emulated= ch(X_np)

ch.sin(X_np)

array([ 0.98144531,  0.38964844,  0.82958984, ...,  0.49438477,
       -0.03292847,  0.96289062])

In [3]:
np.sin(X_np)

array([ 0.9814571 ,  0.38955326,  0.82966963, ...,  0.49435255,
       -0.03292252,  0.96298126])

In [4]:
X_th = torch.from_numpy(X_np.astype(np.float32)) # torch array

# X_jx = jax.numpy.asarray(X_np)
pychop.backend('torch')

In [5]:
ch = Chop('h', rmode=1, subnormal=0)
emulated= ch(X_th)

ch.sin(X_th)

tensor([ 0.9814,  0.3896,  0.8296,  ...,  0.4944, -0.0329,  0.9629])

In [6]:
ch.sin(X_th).dtype

torch.float32

In [7]:
pychop.backend('jax')
X_jx = jax.numpy.asarray(X_np)

ch = Chop('h', rmode=1, subnormal=0)
emulated= ch(X_jx)

ch.sin(X_jx).dtype

dtype('float32')